### PR TITLE
Make the title more searchable friendly and standard

### PR DESCRIPTION
**Pull request by zhimin-z**
Thanks!

### CODE REVIEW

**Comment by taishi-i** [comment]
Thank you for your suggestion. I'm sorry, but we cannot make changes as it needs to be consistent with the notation of the repository.

**Comment by zhimin-z** [comment]
@taishi-i Thanks for your reply.
I have no means to break your custom. Just to keep with your habit as shown in the hugging face interface:
image
This name would be more searchable than before.

**Comment by taishi-i** [comment]
I apologize. The inconsistency in the naming on the Hugging Face site is due to my mistake. Ideally, I'd like to standardize to this repository name.

**Comment by zhimin-z** [comment]
> I apologize. The inconsistency in the naming on the Hugging Face site is due to my mistake. Ideally, I'd like to standardize to this repository name.

Thanks for your reply, I wonder why we use hyphen-separated cases for repo names, actually, a great portion of repo names do NOT have a hyphen at all, only GitHub website adds hyphens exclusively for HTTP link purposes.

**Pull request merged**
