### PR TITLE
Add Co-Developer GPT engine

### PR DESCRIPTION
**Pull request by stoerr**
The free Co-Developer GPT engine serves in OpenAI GPTs and as ChatGPT plugin to give ChatGPT in the chat the ability to modify the files in the directory it is started in, and thus makes it possible to discuss code without copying and pasting it there, and to let ChatGPT write code / modify, even run build actions fixing problems until they work.

https://CoDeveloperGPTengine.stoerr.net/ 
https://github.com/stoerr/CoDeveloperGPTengine 
https://www.youtube.com/watch?v=ubBhv2PUSEs 

Language: Java
Licence:  Apache-2.0

### CODE REVIEW

**Comment by stoerr** [comment]
Sorry, had a little trouble pulling in the upstream changes. 😄

**Review by taishi-i — CHANGES_REQUESTED** [review]
Hi @stoerr! Thank you for the pull request! In this repository, we only post information about GitHub repositories. Therefore, could you please send another pull request with just this link https://github.com/stoerr/CoDeveloperGPTengine added? We will merge that.

**Comment by stoerr** [comment]
Ah, OK. I changed this PR accordingly. Is that fine? Thank you!

**Review by taishi-i — APPROVED** [review]
Hi @stoerr! Thank you for providing information of the repository. I've merged your pull request. Additionally, I will be making the description of the repository multilingual today, so please wait a little while.

**Comment by stoerr** [comment]
I'm sorry! I just realized that I lost the overview and accidentally put this in the wrong section (browser extensions instead of OpenAI). I added the fix for that to https://github.com/taishi-i/awesome-ChatGPT-repositories/pull/45 .

**Pull request merged**
